version: '3.8'
services:
    php:
        container_name: php
        build:
            context: ./
            dockerfile: images/php/Dockerfile
            args:
                APP_PATH: php
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - "8080:80"
        networks:
            - poc-network
        volumes:
            - ./apache-config-php.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./ports-php.conf:/etc/apache2/ports.conf
            - type: bind
              source: ./src/php
              target: /var/www/html/php
    php-custom:
        container_name: php-custom
        build:
            context: ./
            dockerfile: images/php/Dockerfile
            args:
                APP_PATH: php-custom
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - "8082:82"
        networks:
            - poc-network
        volumes:
            - ./apache-config-php-custom.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./ports-php-custom.conf:/etc/apache2/ports.conf
            - type: bind
              source: ./src/php-custom
              target: /var/www/html/php-custom
    mysql:
        platform: linux/x86_64
        container_name: mysql
        image: mysql
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            - poc-network
            - poc-database-network
        volumes:
            - ./storage/mysql:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        ports:
            - "3305:80"
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: ""
        depends_on:
            - mysql
        networks:
            - poc-database-network
volumes:
    src:
networks:
  poc-network:
  poc-database-network:
